[package]
name = "linkerd_parser_tcp_lib"
version = "0.1.0"
authors = ["Carlos B <carlos.baezruiz@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1.0"
bytes = "0.4.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

chrono="0.4"

